// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file runner/v1/service.proto (package runner.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file runner/v1/service.proto.
 */
export const file_runner_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChdydW5uZXIvdjEvc2VydmljZS5wcm90bxIJcnVubmVyLnYxIkkKIUNyZWF0ZVRvb2xBcHByb3ZhbFJlc3BvbnNlUmVxdWVzdBISCgpyZXF1ZXN0X2lkGAEgASgJEhAKCGFwcHJvdmVkGAIgASgIIiQKIkNyZWF0ZVRvb2xBcHByb3ZhbFJlc3BvbnNlUmVzcG9uc2UyjAEKDVJ1bm5lclNlcnZpY2USewoaQ3JlYXRlVG9vbEFwcHJvdmFsUmVzcG9uc2USLC5ydW5uZXIudjEuQ3JlYXRlVG9vbEFwcHJvdmFsUmVzcG9uc2VSZXF1ZXN0Gi0ucnVubmVyLnYxLkNyZWF0ZVRvb2xBcHByb3ZhbFJlc3BvbnNlUmVzcG9uc2UiAEI4WjZnaXRodWIuY29tL3J5b3RhcmFpL2NvZGUtYnJpZGdlL2dlbi9ydW5uZXIvdjE7cnVubmVydjFiBnByb3RvMw");

/**
 * @generated from message runner.v1.CreateToolApprovalResponseRequest
 */
export type CreateToolApprovalResponseRequest = Message<"runner.v1.CreateToolApprovalResponseRequest"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: bool approved = 2;
   */
  approved: boolean;
};

/**
 * Describes the message runner.v1.CreateToolApprovalResponseRequest.
 * Use `create(CreateToolApprovalResponseRequestSchema)` to create a new message.
 */
export const CreateToolApprovalResponseRequestSchema: GenMessage<CreateToolApprovalResponseRequest> = /*@__PURE__*/
  messageDesc(file_runner_v1_service, 0);

/**
 * @generated from message runner.v1.CreateToolApprovalResponseResponse
 */
export type CreateToolApprovalResponseResponse = Message<"runner.v1.CreateToolApprovalResponseResponse"> & {
};

/**
 * Describes the message runner.v1.CreateToolApprovalResponseResponse.
 * Use `create(CreateToolApprovalResponseResponseSchema)` to create a new message.
 */
export const CreateToolApprovalResponseResponseSchema: GenMessage<CreateToolApprovalResponseResponse> = /*@__PURE__*/
  messageDesc(file_runner_v1_service, 1);

/**
 * @generated from service runner.v1.RunnerService
 */
export const RunnerService: GenService<{
  /**
   * @generated from rpc runner.v1.RunnerService.CreateToolApprovalResponse
   */
  createToolApprovalResponse: {
    methodKind: "unary";
    input: typeof CreateToolApprovalResponseRequestSchema;
    output: typeof CreateToolApprovalResponseResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_runner_v1_service, 0);

