// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file manager/v1/service.proto (package manager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file manager/v1/service.proto.
 */
export const file_manager_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChhtYW5hZ2VyL3YxL3NlcnZpY2UucHJvdG8SCm1hbmFnZXIudjEiRQoaQ3JlYXRlQ2xhdWRlQ29kZUxvZ1JlcXVlc3QSFAoMcGF5bG9hZF9qc29uGAEgASgJEhEKCXRocmVhZF9pZBgCIAEoCSIdChtDcmVhdGVDbGF1ZGVDb2RlTG9nUmVzcG9uc2UiPwocQ3JlYXRlUHJvZ3Jlc3NNZXNzYWdlUmVxdWVzdBIMCgR0ZXh0GAEgASgJEhEKCXRocmVhZF9pZBgCIAEoCSIfCh1DcmVhdGVQcm9ncmVzc01lc3NhZ2VSZXNwb25zZSKUAQogQ3JlYXRlVG9vbEFwcHJvdmFsUmVxdWVzdFJlcXVlc3QSEgoKcmVxdWVzdF9pZBgBIAEoCRIRCgl0b29sX25hbWUYAiABKAkSDQoFaW5wdXQYAyABKAkSEQoJdGhyZWFkX2lkGAQgASgJEhUKDXBvZF9uYW1lc3BhY2UYBSABKAkSEAoIcG9kX25hbWUYBiABKAkiIwohQ3JlYXRlVG9vbEFwcHJvdmFsUmVxdWVzdFJlc3BvbnNlMuYCCg5NYW5hZ2VyU2VydmljZRJoChNDcmVhdGVDbGF1ZGVDb2RlTG9nEiYubWFuYWdlci52MS5DcmVhdGVDbGF1ZGVDb2RlTG9nUmVxdWVzdBonLm1hbmFnZXIudjEuQ3JlYXRlQ2xhdWRlQ29kZUxvZ1Jlc3BvbnNlIgASbgoVQ3JlYXRlUHJvZ3Jlc3NNZXNzYWdlEigubWFuYWdlci52MS5DcmVhdGVQcm9ncmVzc01lc3NhZ2VSZXF1ZXN0GikubWFuYWdlci52MS5DcmVhdGVQcm9ncmVzc01lc3NhZ2VSZXNwb25zZSIAEnoKGUNyZWF0ZVRvb2xBcHByb3ZhbFJlcXVlc3QSLC5tYW5hZ2VyLnYxLkNyZWF0ZVRvb2xBcHByb3ZhbFJlcXVlc3RSZXF1ZXN0Gi0ubWFuYWdlci52MS5DcmVhdGVUb29sQXBwcm92YWxSZXF1ZXN0UmVzcG9uc2UiAEI6WjhnaXRodWIuY29tL3J5b3RhcmFpL2NvZGUtYnJpZGdlL2dlbi9tYW5hZ2VyL3YxO21hbmFnZXJ2MWIGcHJvdG8z");

/**
 * @generated from message manager.v1.CreateClaudeCodeLogRequest
 */
export type CreateClaudeCodeLogRequest = Message<"manager.v1.CreateClaudeCodeLogRequest"> & {
  /**
   * @generated from field: string payload_json = 1;
   */
  payloadJson: string;

  /**
   * e.g. "slack/CHANNEL_ID/THREAD_ID"
   *
   * @generated from field: string thread_id = 2;
   */
  threadId: string;
};

/**
 * Describes the message manager.v1.CreateClaudeCodeLogRequest.
 * Use `create(CreateClaudeCodeLogRequestSchema)` to create a new message.
 */
export const CreateClaudeCodeLogRequestSchema: GenMessage<CreateClaudeCodeLogRequest> = /*@__PURE__*/
  messageDesc(file_manager_v1_service, 0);

/**
 * @generated from message manager.v1.CreateClaudeCodeLogResponse
 */
export type CreateClaudeCodeLogResponse = Message<"manager.v1.CreateClaudeCodeLogResponse"> & {
};

/**
 * Describes the message manager.v1.CreateClaudeCodeLogResponse.
 * Use `create(CreateClaudeCodeLogResponseSchema)` to create a new message.
 */
export const CreateClaudeCodeLogResponseSchema: GenMessage<CreateClaudeCodeLogResponse> = /*@__PURE__*/
  messageDesc(file_manager_v1_service, 1);

/**
 * @generated from message manager.v1.CreateProgressMessageRequest
 */
export type CreateProgressMessageRequest = Message<"manager.v1.CreateProgressMessageRequest"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * @generated from field: string thread_id = 2;
   */
  threadId: string;
};

/**
 * Describes the message manager.v1.CreateProgressMessageRequest.
 * Use `create(CreateProgressMessageRequestSchema)` to create a new message.
 */
export const CreateProgressMessageRequestSchema: GenMessage<CreateProgressMessageRequest> = /*@__PURE__*/
  messageDesc(file_manager_v1_service, 2);

/**
 * @generated from message manager.v1.CreateProgressMessageResponse
 */
export type CreateProgressMessageResponse = Message<"manager.v1.CreateProgressMessageResponse"> & {
};

/**
 * Describes the message manager.v1.CreateProgressMessageResponse.
 * Use `create(CreateProgressMessageResponseSchema)` to create a new message.
 */
export const CreateProgressMessageResponseSchema: GenMessage<CreateProgressMessageResponse> = /*@__PURE__*/
  messageDesc(file_manager_v1_service, 3);

/**
 * @generated from message manager.v1.CreateToolApprovalRequestRequest
 */
export type CreateToolApprovalRequestRequest = Message<"manager.v1.CreateToolApprovalRequestRequest"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: string tool_name = 2;
   */
  toolName: string;

  /**
   * @generated from field: string input = 3;
   */
  input: string;

  /**
   * @generated from field: string thread_id = 4;
   */
  threadId: string;

  /**
   * @generated from field: string pod_namespace = 5;
   */
  podNamespace: string;

  /**
   * @generated from field: string pod_name = 6;
   */
  podName: string;
};

/**
 * Describes the message manager.v1.CreateToolApprovalRequestRequest.
 * Use `create(CreateToolApprovalRequestRequestSchema)` to create a new message.
 */
export const CreateToolApprovalRequestRequestSchema: GenMessage<CreateToolApprovalRequestRequest> = /*@__PURE__*/
  messageDesc(file_manager_v1_service, 4);

/**
 * @generated from message manager.v1.CreateToolApprovalRequestResponse
 */
export type CreateToolApprovalRequestResponse = Message<"manager.v1.CreateToolApprovalRequestResponse"> & {
};

/**
 * Describes the message manager.v1.CreateToolApprovalRequestResponse.
 * Use `create(CreateToolApprovalRequestResponseSchema)` to create a new message.
 */
export const CreateToolApprovalRequestResponseSchema: GenMessage<CreateToolApprovalRequestResponse> = /*@__PURE__*/
  messageDesc(file_manager_v1_service, 5);

/**
 * @generated from service manager.v1.ManagerService
 */
export const ManagerService: GenService<{
  /**
   * @generated from rpc manager.v1.ManagerService.CreateClaudeCodeLog
   */
  createClaudeCodeLog: {
    methodKind: "unary";
    input: typeof CreateClaudeCodeLogRequestSchema;
    output: typeof CreateClaudeCodeLogResponseSchema;
  },
  /**
   * @generated from rpc manager.v1.ManagerService.CreateProgressMessage
   */
  createProgressMessage: {
    methodKind: "unary";
    input: typeof CreateProgressMessageRequestSchema;
    output: typeof CreateProgressMessageResponseSchema;
  },
  /**
   * @generated from rpc manager.v1.ManagerService.CreateToolApprovalRequest
   */
  createToolApprovalRequest: {
    methodKind: "unary";
    input: typeof CreateToolApprovalRequestRequestSchema;
    output: typeof CreateToolApprovalRequestResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_manager_v1_service, 0);

